# Generated by Django 5.2 on 2025-05-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sneakers/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='sneaker',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL-slug'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL изображения'),
        ),
    ]
