# Generated by Django 5.2 on 2025-05-06 11:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sneaker_image_sneaker_slug_alter_sneaker_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.sneaker_image_path, verbose_name='Изображение'),
        ),
    ]
